# Generated by Django 3.1.7 on 2021-03-25 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conditions',
            name='severity',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Low'), (2, 'Mid'), (3, 'High')], default=1),
        ),
    ]
