# Generated by Django 3.1.7 on 2021-03-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condition', '0002_auto_20210325_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conditions',
            name='severity',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Not'), (1, 'Low'), (2, 'Mid'), (3, 'High')], default=1),
        ),
    ]
