# Generated by Django 3.1.7 on 2021-03-25 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condition', '0003_auto_20210325_1733'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Conditions',
            new_name='Condition',
        ),
    ]
