# Generated by Django 3.1.7 on 2021-03-26 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condition', '0007_auto_20210326_0225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condition',
            name='patient',
        ),
    ]
