# Generated by Django 3.1.7 on 2021-03-26 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
        ('condition', '0008_remove_condition_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.patient'),
        ),
    ]
